# WeatherPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress

# Import API key
from config import weather_api_key

# Incorporated citipy to determine city based on latitude and longitude
from citipy import citipy

# Output File (CSV)
output_data_file = "output_data/cities.csv"

# Range of latitudes and longitudes
lat_range = (-90, 90)
lng_range = (-180, 180)

## Generate Cities List

In [2]:
# List for holding lat_lngs and cities
lat_lngs = []
cities = []
size = 200
# Create a set of random lat and lng combinations
lats = np.random.uniform(lat_range[0], lat_range[1], size=size)
lngs = np.random.uniform(lng_range[0], lng_range[1], size=size)
lat_lngs = zip(lats, lngs)

# Identify nearest city for each lat, lng combination
for lat_lng in lat_lngs:
    city = citipy.nearest_city(lat_lng[0], lat_lng[1]).city_name
    
    # If the city is unique, then add it to a our cities list
    if city not in cities:
        cities.append(city)
# Print the city count to confirm sufficient count
num_cities = len(cities)
num_cities
cities_no_clean_df = pd.DataFrame(cities, columns =['City'])
cities_no_clean_df.head(20)

              City
0     puerto ayora
1       boa viagem
2        taolanaro
3         hermanus
4          lahaina
5            bluff
6        busselton
7          haapiti
8        kilindoni
9          rikitea
10        zyryanka
11   alice springs
12  saint-philippe
13       jamestown
14       upernavik
15        ruatoria
16        cherskiy
17          shache
18  port elizabeth
19    punta arenas

### Perform API Calls
* Perform a weather check on each city using a series of successive API calls.
* Include a print log of each city as it'sbeing processed (with the city number and city name).

In [9]:
url = "http://api.openweathermap.org/data/2.5/weather?"
units = 'imperial'


cities_no_clean_df['Latitude'] = ""
cities_no_clean_df['Longitude'] = ""
cities_no_clean_df['Temperature'] = ""

skipped_row = []
# Build query URL
#query_url = url + 'lat=' + latitud + '&lon=' + longitud + "&appid=" + api_key + "&units=metric"

for index, row in cities_no_clean_df.iterrows():
    city_name = row['City']

    
    cities_url = url + 'q=' + city_name   + '&appid=' + weather_api_key + '&units=' + units
    city_json = requests.get(cities_url).json()
    try:
        
        cities_no_clean_df.loc[index,'Latitude'] = city_json['coord']['lat']
        cities_no_clean_df.loc[index,'Longitude'] = city_json['coord']['lon']
        cities_no_clean_df.loc[index,'Temperature'] = city_json['main']['temp']
        print(f'{city_name} is being processed. {index + 1} of {num_cities} ')
        
    except (KeyError, IndexError):
        print(f"Missing field/result... skipping row {index + 1} .")
        cities_no_clean_df.loc[index,'Latitude'] = None
        cities_no_clean_df.loc[index,'Longitude'] = None
        cities_no_clean_df.loc[index,'Temperature'] = None
        skipped_row.append(index)
        
    

cities_no_clean_df.head(20)

puerto ayora is being processed. 1 of 136
boa viagem is being processed. 2 of 136
Missing field/result... skipping row 3 .
hermanus is being processed. 4 of 136
lahaina is being processed. 5 of 136
bluff is being processed. 6 of 136
busselton is being processed. 7 of 136
haapiti is being processed. 8 of 136
kilindoni is being processed. 9 of 136
rikitea is being processed. 10 of 136
zyryanka is being processed. 11 of 136
alice springs is being processed. 12 of 136
saint-philippe is being processed. 13 of 136
jamestown is being processed. 14 of 136
upernavik is being processed. 15 of 136
Missing field/result... skipping row 16 .
cherskiy is being processed. 17 of 136
shache is being processed. 18 of 136
port elizabeth is being processed. 19 of 136
punta arenas is being processed. 20 of 136
bengkulu is being processed. 21 of 136
holalkere is being processed. 22 of 136
stepnogorsk is being processed. 23 of 136
bambous virieux is being processed. 24 of 136
aracataca is being processed. 25 of 136
Missing field/result... skipping row 26 .
tiksi is being processed. 27 of 136
Missing field/result... skipping row 28 .
abbeville is being processed. 29 of 136
alpena is being processed. 30 of 136
severo-kurilsk is being processed. 31 of 136
zhaotong is being processed. 32 of 136
hithadhoo is being processed. 33 of 136
luderitz is being processed. 34 of 136
nova olimpia is being processed. 35 of 136
avarua is being processed. 36 of 136
gagnoa is being processed. 37 of 136
lorengau is being processed. 38 of 136
butaritari is being processed. 39 of 136
asilah is being processed. 40 of 136
ancud is being processed. 41 of 136
Missing field/result... skipping row 42 .
kenai is being processed. 43 of 136
sultanpur is being processed. 44 of 136
sobolevo is being processed. 45 of 136
starokamyshinsk is being processed. 46 of 136
carnarvon is being processed. 47 of 136
tuktoyaktuk is being processed. 48 of 136
Missing field/result... skipping row 49 .
hilo is being processed. 50 of 136
mangrol is being processed. 51 of 136
boueni is being processed. 52 of 136
mataura is being processed. 53 of 136
Missing field/result... skipping row 54 .
atuona is being processed. 55 of 136
cayenne is being processed. 56 of 136
mitsamiouli is being processed. 57 of 136
muroto is being processed. 58 of 136
geraldton is being processed. 59 of 136
chokurdakh is being processed. 60 of 136
ishigaki is being processed. 61 of 136
honiara is being processed. 62 of 136
kloulklubed is being processed. 63 of 136
saint george is being processed. 64 of 136
nikolskoye is being processed. 65 of 136
moose factory is being processed. 66 of 136
vaini is being processed. 67 of 136
bubaque is being processed. 68 of 136
iqaluit is being processed. 69 of 136
camana is being processed. 70 of 136
albany is being processed. 71 of 136
Missing field/result... skipping row 72 .
port blair is being processed. 73 of 136
laguna is being processed. 74 of 136
qeshm is being processed. 75 of 136
chernyshevskiy is being processed. 76 of 136
hobart is being processed. 77 of 136
zhovti vody is being processed. 78 of 136
fandriana is being processed. 79 of 136
cape town is being processed. 80 of 136
ixtapa is being processed. 81 of 136
hami is being processed. 82 of 136
salinopolis is being processed. 83 of 136
new norfolk is being processed. 84 of 136
port alfred is being processed. 85 of 136
lerwick is being processed. 86 of 136
flin flon is being processed. 87 of 136
cockburn town is being processed. 88 of 136
Missing field/result... skipping row 89 .
ushuaia is being processed. 90 of 136
xuddur is being processed. 91 of 136
Missing field/result... skipping row 92 .
ribeira grande is being processed. 93 of 136
constitucion is being processed. 94 of 136
nantucket is being processed. 95 of 136
Missing field/result... skipping row 96 .
merauke is being processed. 97 of 136
Missing field/result... skipping row 98 .
Missing field/result... skipping row 99 .
puro is being processed. 100 of 136
sao filipe is being processed. 101 of 136
petropavl is being processed. 102 of 136
brae is being processed. 103 of 136
qaanaaq is being processed. 104 of 136
hammerfest is being processed. 105 of 136
Missing field/result... skipping row 106 .
broome is being processed. 107 of 136
pisco is being processed. 108 of 136
Missing field/result... skipping row 109 .
ponta do sol is being processed. 110 of 136
san quintin is being processed. 111 of 136
yara is being processed. 112 of 136
bida is being processed. 113 of 136
beisfjord is being processed. 114 of 136
cururupu is being processed. 115 of 136
goderich is being processed. 116 of 136
bredasdorp is being processed. 117 of 136
chapais is being processed. 118 of 136
palu is being processed. 119 of 136
stratford is being processed. 120 of 136
port hardy is being processed. 121 of 136
Missing field/result... skipping row 122 .
estelle is being processed. 123 of 136
najran is being processed. 124 of 136
hasaki is being processed. 125 of 136
palmer is being processed. 126 of 136
victor harbor is being processed. 127 of 136
nelson bay is being processed. 128 of 136
sorland is being processed. 129 of 136
mahebourg is being processed. 130 of 136
arraial do cabo is being processed. 131 of 136
xai-xai is being processed. 132 of 136
porto uniao is being processed. 133 of 136
rio grande is being processed. 134 of 136
mar del plata is being processed. 135 of 136
high rock is being processed. 136 of 136

              City Latitude Longitude Temperature
0     puerto ayora  -0.7393  -90.3518        80.6
1       boa viagem  -5.1275  -39.7322       74.61
2        taolanaro     None      None        None
3         hermanus -34.4187   19.2345       51.01
4          lahaina  20.8783  -156.683       78.26
5            bluff    -46.6   168.333          57
6        busselton   -33.65   115.333       59.22
7          haapiti -17.5667  -149.867       84.09
8        kilindoni  -7.9139   39.6668       80.24
9          rikitea -23.1203  -134.969       76.21
10        zyryanka    65.75    150.85       29.86
11   alice springs    -23.7   133.883        51.8
12  saint-philippe -21.3585   55.7679       69.03
13       jamestown   42.097  -79.2353       69.01
14       upernavik  72.7868  -56.1549       23.65
15        ruatoria     None      None        None
16        cherskiy    68.75     161.3       28.49
17          shache  38.4167   77.2406       62.38
18  port elizabeth  -33.918   25.5701        60.8
19    punta arenas   -53.15  -70.9167          41

{'coord': {'lon': -91.9167, 'lat': 14.3},
 'weather': [{'id': 802,
   'main': 'Clouds',
   'description': 'scattered clouds',
   'icon': '03d'}],
 'base': 'stations',
 'main': {'temp': 82.67,
  'feels_like': 83.19,
  'temp_min': 75,
  'temp_max': 89.6,
  'pressure': 1015,
  'humidity': 48},
 'visibility': 9000,
 'wind': {'speed': 6.91, 'deg': 210},
 'clouds': {'all': 40},
 'dt': 1619633563,
 'sys': {'type': 1,
  'id': 7068,
  'country': 'GT',
  'sunrise': 1619610392,
  'sunset': 1619655805},
 'timezone': -21600,
 'id': 3598787,
 'name': 'Champerico',
 'cod': 200}

### Convert Raw Data to DataFrame
* Export the city data into a .csv.
* Display the DataFrame

In [17]:
cities_df = cities_no_clean_df.dropna().reset_index(drop=True)

cities_df.to_csv(output_data_file, index = False)
cities_df.head()

           City Latitude Longitude Temperature
0  puerto ayora  -0.7393  -90.3518        80.6
1    boa viagem  -5.1275  -39.7322       74.61
2      hermanus -34.4187   19.2345       51.01
3       lahaina  20.8783  -156.683       78.26
4         bluff    -46.6   168.333          57

## Inspect the data and remove the cities where the humidity > 100%.
----
Skip this step if there are no cities that have humidity > 100%.

In [ ]:
#  Get the indices of cities that have humidity over 100%.

In [ ]:
# Make a new DataFrame equal to the city data to drop all humidity outliers by index.
# Passing "inplace=False" will make a copy of the city_data DataFrame, which we call "clean_city_data".

## Plotting the Data
* Use proper labeling of the plots using plot titles (including date of analysis) and axes labels.
* Save the plotted figures as .pngs.

## Latitude vs. Temperature Plot

## Latitude vs. Humidity Plot

## Latitude vs. Cloudiness Plot

## Latitude vs. Wind Speed Plot

## Linear Regression

####  Northern Hemisphere - Max Temp vs. Latitude Linear Regression

####  Southern Hemisphere - Max Temp vs. Latitude Linear Regression

####  Northern Hemisphere - Humidity (%) vs. Latitude Linear Regression

####  Southern Hemisphere - Humidity (%) vs. Latitude Linear Regression

####  Northern Hemisphere - Cloudiness (%) vs. Latitude Linear Regression

####  Southern Hemisphere - Cloudiness (%) vs. Latitude Linear Regression

####  Northern Hemisphere - Wind Speed (mph) vs. Latitude Linear Regression

####  Southern Hemisphere - Wind Speed (mph) vs. Latitude Linear Regression